### ISSUE TITLE
Rich-text editors don't load when a quest submission bounces back with a validation error

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#2608]
Found while capturing screenshots for #2560.

### The problem

`submission.html` pulls in the summernote library through the comment form's media:

```django
{# the comment box is a summernote editor too, so its media covers the answer editors #}
{{ submission_form.media }}
```

That holds on the GET path, where `submission()` builds the full `SubmissionForm` (its `comment_text` uses `ByteDeckSummernoteSafeInplaceWidget`). It does not hold on the POST path. When a submission fails validation, `complete()` re-renders the same template with the form it built for the POST, and with no files and no custom XP that is `SubmissionQuickReplyFormStudent`, whose `comment_text` is a plain `forms.Textarea(attrs={'rows': 2})` (`quest_manager/forms.py:396`). It has no summernote media, so nothing loads.

The question answer editors are summernote widgets of their own, but a widget's media only reaches the page through the form that renders it, and the template asks only `submission_form`. So on the re-render **every editor on the page fails to initialize**, not just the comment box.

### Reproducing it

On a `hackerspace` dev deck: a quest with a required long-answer question, submitted with the editor left empty. Measured in the browser on the same page, before and after the bounce:

| | fresh GET | error re-render |
| --- | --- | --- |
| `.note-editable` elements | 2 | 0 |
| `typeof jQuery.fn.summernote` | `function` | `undefined` |
| page errors | none | `$sn.summernote is not a function` |

(The only failed network requests on either load are optional CodeMirror/KaTeX CDN extras, which fail on the fresh page too while the editor still works, so they are not the cause.)

### Impact

A student who gets bounced (a blank required answer, a rejected file type, a quick-reply form on a custom-XP quest) lands on a page where the editors have turned into raw textareas showing raw HTML. Their previous answer is displayed to them as literal markup:

```
<p><br></p><p><br></p><p><br></p>
```

They have no formatting tools, cannot paste an image, and whatever they type is submitted as plain text. Nothing on the page says anything is wrong. This is the page a student sees at precisely the moment they are being asked to correct a mistake.

![The re-rendered form showing raw markup in a plain textarea instead of an editor](https://raw.githubusercontent.com/bytedeck/bytedeck/pr-assets/2608/rerender-raw-textarea.png)

### Notes toward a fix

The template needs the answer formset's media as well as the form's, without loading the assets twice on the GET path where the full form already supplies them (`test_submission_page__summernote_assets_load_once` guards that). Combining them in the view, where `Media` objects can be added (`form.media + question_formset.media`, which dedupes), is probably cleaner than trying to do it in the template.

Worth deciding at the same time whether the POST path should just build the same form class as the GET path. The quick-reply form is chosen as an optimization for the common comment case, but it is also why a re-rendered submission page differs from the one the student was just looking at.

This is pre-existing and not caused by #2560, but that fix routes many more students onto this path: a blank required long answer now bounces where it previously completed.

- Claude Code (`bytedeck - single session`)

**Comment by tylerecouture** [comment]
Picking this up (I filed it while working on #2560).

Plan: combine the media in the view, where `Media` objects add and de-duplicate, rather than emitting a second `{{ ... .media }}` in the template. `form.media + question_formset.media` gives one combined set, so the GET path keeps loading the assets exactly once (which `test_submission_page__summernote_assets_load_once` already pins) while the POST re-render gains the answer editors' media that the quick-reply form does not carry.

I am not planning to change which form class the POST path builds, even though that is the root of the asymmetry. Swapping `SubmissionQuickReplyFormStudent` for the full `SubmissionForm` would change what gets validated and stored on every comment, which is a much larger blast radius than this bug warrants. Worth doing separately if it is wanted; noting it here so the option is not lost.

Verification will be a browser measurement rather than a unit test, since what is broken is whether a library initializes: `typeof jQuery.fn.summernote` and the `.note-editable` count on a fresh GET versus the error re-render, plus a check that no `$sn.summernote is not a function` page error fires. I will add a Django test asserting the summernote assets appear in the re-rendered response too, since that part is testable server-side.

- Claude Code (`bytedeck - single session`)

---
_Generated by [Claude Code](https://claude.ai/code)_
